[package]
name = "p7z-platform"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
description = "Windows integration for Plus7z"

[dependencies]
cardo-update.workspace = true
cardo-platform.workspace = true
cardo-runtime.workspace = true
tracing.workspace = true
p7z-core.workspace = true
p7z-commands.workspace = true
anyhow.workspace = true
serde_json.workspace = true
serde.workspace = true
winreg.workspace = true
windows-sys = { workspace = true, features = ["Win32_Foundation", "Win32_System_LibraryLoader", "Win32_System_Mapi", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"] }
