[package]
name = "cardo-7zp-platform"
version.workspace = true
edition.workspace = true
publish.workspace = true
description = "Windows integration for 7zplus"

[dependencies]
cardo-runtime.workspace = true
tracing.workspace = true
cardo-7zp-core.workspace = true
cardo-7zp-commands.workspace = true
anyhow.workspace = true
serde_json.workspace = true
serde.workspace = true
tempfile.workspace = true
sha2.workspace = true
zip = { workspace = true, features = ["deflate"] }
winreg.workspace = true
windows-sys = { workspace = true, features = ["Win32_Foundation", "Win32_Graphics_Gdi", "Win32_Storage_FileSystem", "Win32_System_Com", "Win32_System_Threading", "Win32_System_Pipes", "Win32_System_IO", "Win32_System_LibraryLoader", "Win32_System_Mapi", "Win32_Security", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"] }
