[package]
name = "zip-core"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
description = "Shared preferences and localization for Plus7z"

[dependencies]
cardo-runtime.workspace = true
anyhow.workspace = true
serde.workspace = true
fluent-bundle.workspace = true
windows-sys = { workspace = true, features = ["Win32_Globalization"] }
