[package]
name = "cardo-7zp-app"
version.workspace = true
edition.workspace = true
publish.workspace = true
description = "Native Windows archive manager built with GPUI Kit"

[[bin]]
name = "7zplus"
path = "src/main.rs"

[dependencies]
cardo-runtime.workspace = true
tracing.workspace = true
cardo-7zp-core.workspace = true
cardo-7zp-platform.workspace = true
cardo-7zp-ui.workspace = true
anyhow.workspace = true
gpui-kit.workspace = true
rfd.workspace = true

[build-dependencies]
embed-resource = "=3.0.11"
